spring:
  profiles:
    default: local
    group:
      "local": "local, local-confidential"
      "dev": "dev, dev-confidential"
      "prod": "prod, prod-confidential"
      "test": "test, test-confidential"
  jackson:
    default-property-inclusion: always

server:
  port: 8080
  error:
    include-stacktrace: always

decorator:
  datasource:
    datasource-proxy:
      query:
        log-level: info
        logger-name: datasource-proxy
      format-sql: true

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/letmedowith_app
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    generate-ddl: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    url: jdbc:mysql://localhost:3306/letmedowith_app
  batch:
    jdbc:
      initialize-schema: always   # 운영은 보통 'never'로 두고 DDL 미리 반영
    job:
      enabled: false

logging:
  level:
    com.LetMeDoWith.LetMeDoWith: info
    root: info
#    datasource-proxy: off


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_SCHEMA}
    hikari:
      leak-detection-threshold: 20000
  #  data:
  #    redis:
  #      host: ${REDIS_URL}
  #      port: ${REDIS_PORT}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: false
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_SCHEMA}
  batch:
    jdbc:
      initialize-schema: always   # 운영은 보통 'never'로 두고 DDL 미리 반영
    job:
      enabled: false

logging:
  level:
    com:
      LetMeDoWith.LetMeDoWith: info
      zaxxer.hikari: debug
    root: info
    datasource-proxy: off

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s %b %D'
      directory: /var/logs/access-log
      prefix: access
      suffix: .log
      file-date-format: .yyyy-MM-dd
      max-days: 7
      rotate: true
    remoteip:
      remote-ip-header: X-Forwarded-For
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/letmedowith_app
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: never   # 운영은 보통 'never'로 두고 DDL 미리 반영
    job:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/letmedowith_app
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: false
    url: jdbc:mysql://localhost:3306/letmedowith_app
  batch:
    jdbc:
      initialize-schema: always   # 운영은 보통 'never'로 두고 DDL 미리 반영
    job:
      enabled: false

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
    springframework:
      jdbc:
        datasource:
          init:
            ScriptUtils: debug
      batch: debug
    com.LetMeDoWith.LetMeDoWith: info
    root: info