server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/letmedowith_app
    username: letmedowith
    password: letmedowith@admin#2024

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
    url: jdbc:mysql://localhost:3306/letmedowith_app
    user: letmedowith
    password: letmedowith@admin#2024

