INSERT INTO notification_template (code,
                                   type,
                                   title,
                                   body,
                                   image_url,
                                   app_deep_link,
                                   created_at,
                                   updated_at,
                                   created_by,
                                   updated_by)
VALUES ('DAILY_MON_AM',
        'NORMAL',
        '☀️ 월요일 아침, 이번 주도 화이팅!',
        '오늘의 두윗을 확인하고 하루를 힘차게 시작해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_MON_PM',
        'NORMAL',
        '🌙 월요일 하루 어떠셨나요?',
        '오늘 남은 두윗이 있다면 지금 마무리해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_TUES_AM',
        'NORMAL',
        '☀️ 화요일 아침이에요',
        '오늘의 두윗을 확인하고 하루를 시작해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_TUES_PM',
        'NORMAL',
        '🌙 화요일 하루 어떠셨나요?',
        '오늘 남은 두윗이 있다면 지금 마무리해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_WED_AM',
        'NORMAL',
        '☀️ 벌써 수요일이에요',
        '오늘의 두윗을 확인하고 하루를 시작해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_WED_PM',
        'NORMAL',
        '🌙 한 주의 절반을 지나왔어요',
        '오늘 남은 두윗이 있다면 지금 마무리해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_THURS_AM',
        'NORMAL',
        '☀️ 목요일 아침이에요',
        '오늘의 두윗을 확인하고 하루를 시작해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_THURS_PM',
        'NORMAL',
        '🌙 목요일 하루 어떠셨나요?',
        '오늘 남은 두윗이 있다면 지금 마무리해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_FRI_AM',
        'NORMAL',
        '☀️ 불금 아침이에요',
        '오늘의 두윗을 확인하고 하루를 시작해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_FRI_PM',
        'NORMAL',
        '🌙 한 주 마무리 잘 하고 계신가요?',
        '오늘 남은 두윗이 있다면 지금 마무리해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_SAT_AM',
        'NORMAL',
        '☀️ 즐거운 토요일 아침이에요',
        '오늘의 두윗을 확인하고 여유로운 하루를 시작해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_SAT_PM',
        'NORMAL',
        '🌙 토요일 하루 어떠셨나요?',
        '오늘 남은 두윗이 있다면 지금 마무리해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_SUN_AM',
        'NORMAL',
        '☀️ 일요일 아침이에요',
        '오늘의 두윗을 확인하고 다음 주를 준비해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('DAILY_SUN_PM',
        'NORMAL',
        '🌙 한 주가 마무리되고 있어요',
        '오늘 남은 두윗이 있다면 지금 마무리하고 새로운 한 주를 준비해보세요',
        NULL,
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system');
