INSERT INTO notification_template (code,
                                   title,
                                   body,
                                   app_deep_link,
                                   create_at,
                                   updated_at,
                                   created_by,
                                   updated_by)
VALUES ('SIGN_UP_COMPLETE',
        '👋 환영해요 {{userName}}님! 회원가입이 완료되었습니다.',
        '프로필을 설정하고 서비스를 시작해 보세요!',
        NULL,
        NOW(),
        NOW(),
        'system',
        'system'),
       ('ENABLE_NOTIFICATION_REQUEST',
        '🔔알림을 켜고 더 재미있게 사용해봐요!',
        '알림이 있어야 두윗러로써의 삶을 제대로 경험할 수 있답니다.\n이제 알림을 켜고 시작해볼까요?',
        NULL,
        NOW(),
        NOW(),
        'system',
        'system');