INSERT INTO notification_template (code,
                                   title,
                                   body,
                                   app_deep_link,
                                   created_at,
                                   updated_at,
                                   created_by,
                                   updated_by)
VALUES ('SIGN_UP_COMPLETE',
        '👋 환영해요 {{userName}}님! 회원가입이 완료되었습니다.',
        '프로필을 설정하고 서비스를 시작해 보세요!',
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('ENABLE_NOTIFICATION_REQUEST',
        '🔔알림을 켜고 더 재미있게 사용해봐요!',
        '알림이 있어야 두윗러로써의 삶을 제대로 경험할 수 있답니다.\n이제 알림을 켜고 시작해볼까요?',
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('FEEDBACK_RECEIVED_1',
        '{{senderNickname}}의 잡도리를 받았어요',
        '{{receiverNickname}}, 아직도 안했구나?',
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('FEEDBACK_RECEIVED_2',
        '{{senderNickname}}의 잡도리를 받았어요',
        '{{receiverNickname}}, 혹시 잡도리 수집중이니?',
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('FEEDBACK_RECEIVED_3',
        '{{senderNickname}}의 잡도리를 받았어요',
        '{{receiverNickname}}, 발등에 불 떨어지고 나서야 하려고?',
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('FEEDBACK_RECEIVED_4',
        '{{senderNickname}}의 잡도리를 받았어요',
        '{{receiverNickname}}님 그러다 또 후회함',
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system'),
       ('LIKE_RECEIVED',
        '공감을 받았어요',
        '{{senderNickname}}님이 도리 인증에 공감했어요',
        'letmedowith://home',
        NOW(),
        NOW(),
        'system',
        'system');